server {
    listen 80;
    server_name localhost;

    location /api/products {
        proxy_pass http://product-service:8000/api/products;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/categories {
        proxy_pass http://product-service:8000/api/categories;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/payments {
        proxy_pass http://payment-service:8001/api/payments;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/invoices {
        proxy_pass http://payment-service:8001/api/invoices;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/coupons {
        proxy_pass http://coupon-service:8002/api/coupons;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/promotions {
        proxy_pass http://coupon-service:8002/api/promotions;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
